// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: WatchTest1

#ifndef UI_DISPLAY_H
#define UI_DISPLAY_H

#ifdef __cplusplus
extern "C" {
#endif

extern void ui_Display_screen_init(void);
extern void ui_Display_screen_destroy(void);
extern void ui_event_Display(lv_event_t * e);
extern lv_obj_t * ui_Display;
extern lv_obj_t * ui_Label2;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
