// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: m5StackTest1

#include "ui.h"

lv_obj_t * ui_Second = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions
void ui_event_Second(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 20, 0, &ui_Main_screen_init);
    }
}

// build funtions

void ui_Second_screen_init(void)
{
    ui_Second = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Second, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Second);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 0);
    lv_obj_set_y(ui_Label2, 0);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "swipe right \nto go back ");

    lv_obj_add_event_cb(ui_Second, ui_event_Second, LV_EVENT_ALL, NULL);

}

void ui_Second_screen_destroy(void)
{
    if(ui_Second) lv_obj_del(ui_Second);

    // NULL screen variables
    ui_Second = NULL;
    ui_Label2 = NULL;

}
