// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: M5StackTest2

#ifndef UI_LAMP_H
#define UI_LAMP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Lamp
extern void ui_Lamp_screen_init(void);
extern void ui_Lamp_screen_destroy(void);
extern void ui_event_Lamp(lv_event_t * e);
extern lv_obj_t * ui_Lamp;
extern lv_obj_t * ui_offon_all_lamps;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

