// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: M5StackTest2

#include "ui.h"

lv_obj_t * ui_Lamp = NULL;
lv_obj_t * ui_offon_all_lamps = NULL;
// event funtions
void ui_event_Lamp(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_MQTT_Info, LV_SCR_LOAD_ANIM_MOVE_BOTTOM, 200, 0, &ui_MQTT_Info_screen_init);
    }
}

// build funtions

void ui_Lamp_screen_init(void)
{
    ui_Lamp = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Lamp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Lamp, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Lamp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_offon_all_lamps = lv_switch_create(ui_Lamp);
    lv_obj_set_width(ui_offon_all_lamps, 200);
    lv_obj_set_height(ui_offon_all_lamps, 100);
    lv_obj_set_align(ui_offon_all_lamps, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_offon_all_lamps, lv_color_hex(0x686868), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offon_all_lamps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_offon_all_lamps, lv_color_hex(0x2E2E2E), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_offon_all_lamps, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Lamp, ui_event_Lamp, LV_EVENT_ALL, NULL);

}

void ui_Lamp_screen_destroy(void)
{
    if(ui_Lamp) lv_obj_del(ui_Lamp);

    // NULL screen variables
    ui_Lamp = NULL;
    ui_offon_all_lamps = NULL;

}
