// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: M5StackTest2

#ifndef UI_MAIN__H
#define UI_MAIN__H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Main_
extern void ui_Main__screen_init(void);
extern void ui_Main__screen_destroy(void);
extern void ui_event_Main_(lv_event_t * e);
extern lv_obj_t * ui_Main_;
extern lv_obj_t * ui_Label1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

