// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: M5StackTest2

#include "ui.h"

lv_obj_t * ui_MQTT_Info = NULL;
lv_obj_t * ui_TextArea1 = NULL;
// event funtions
void ui_event_MQTT_Info(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Main_, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_Main__screen_init);
    }
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Lamp, LV_SCR_LOAD_ANIM_MOVE_TOP, 200, 0, &ui_Lamp_screen_init);
    }
}

// build funtions

void ui_MQTT_Info_screen_init(void)
{
    ui_MQTT_Info = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MQTT_Info, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MQTT_Info, lv_color_hex(0x585858), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MQTT_Info, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_MQTT_Info);
    lv_obj_set_width(ui_TextArea1, 200);
    lv_obj_set_height(ui_TextArea1, 100);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_set_style_bg_color(ui_TextArea1, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0x424242), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0xFFFFFF), LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_TEXTAREA_PLACEHOLDER | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MQTT_Info, ui_event_MQTT_Info, LV_EVENT_ALL, NULL);

}

void ui_MQTT_Info_screen_destroy(void)
{
    if(ui_MQTT_Info) lv_obj_del(ui_MQTT_Info);

    // NULL screen variables
    ui_MQTT_Info = NULL;
    ui_TextArea1 = NULL;

}
