// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: m5StackTest1

#ifndef _M5STACKTEST1_UI_H
#define _M5STACKTEST1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "/home/ramy/Desktop/WorkShop/m5StackTest1"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_Main.h"
#include "ui_Second.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
