// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: m5StackTest1

#ifndef UI_SECOND_H
#define UI_SECOND_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Second
extern void ui_Second_screen_init(void);
extern void ui_Second_screen_destroy(void);
extern void ui_event_Second(lv_event_t * e);
extern lv_obj_t * ui_Second;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

