// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: WatchTest2

#include "ui.h"

lv_obj_t * ui_Main_ = NULL;
lv_obj_t * ui_Label1 = NULL;
// event funtions
void ui_event_Main_(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_State, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_State_screen_init);
    }
}

// build funtions

void ui_Main__screen_init(void)
{
    ui_Main_ = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main_, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Main_, &ui_img_596472271, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Main_);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 3);
    lv_obj_set_y(ui_Label1, -31);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Swipe to go to the next page ");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Main_, ui_event_Main_, LV_EVENT_ALL, NULL);

}

void ui_Main__screen_destroy(void)
{
    if(ui_Main_) lv_obj_del(ui_Main_);

    // NULL screen variables
    ui_Main_ = NULL;
    ui_Label1 = NULL;

}
