// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: WatchTest2

#ifndef UI_STATE_H
#define UI_STATE_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_State
extern void ui_State_screen_init(void);
extern void ui_State_screen_destroy(void);
extern void ui_event_State(lv_event_t * e);
extern lv_obj_t * ui_State;
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

