// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: WatchTest2

#include "ui.h"

lv_obj_t * ui_switch = NULL;
lv_obj_t * ui_Switch1 = NULL;
// event funtions
void ui_event_switch(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_State, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 200, 0, &ui_State_screen_init);
    }
}

// build funtions

void ui_switch_screen_init(void)
{
    ui_switch = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_switch, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_switch, lv_color_hex(0x4E4E4E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_switch, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_switch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_switch, lv_color_hex(0x4E4E4E), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_switch, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_switch);
    lv_obj_set_width(ui_Switch1, 200);
    lv_obj_set_height(ui_Switch1, 100);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    lv_obj_add_event_cb(ui_switch, ui_event_switch, LV_EVENT_ALL, NULL);

}

void ui_switch_screen_destroy(void)
{
    if(ui_switch) lv_obj_del(ui_switch);

    // NULL screen variables
    ui_switch = NULL;
    ui_Switch1 = NULL;

}
