// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: M5StackTest2

#ifndef UI_MQTT_INFO_H
#define UI_MQTT_INFO_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MQTT_Info
extern void ui_MQTT_Info_screen_init(void);
extern void ui_MQTT_Info_screen_destroy(void);
extern void ui_event_MQTT_Info(lv_event_t * e);
extern lv_obj_t * ui_MQTT_Info;
extern lv_obj_t * ui_TextArea1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

